spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/course?characterEncoding=UTF8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
    com :
      example :
        server :
          dao : trace
